-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 13:05:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artist` (
  `artistId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `surName` VARCHAR(45) NOT NULL,
  `DoB` DATE NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NULL,
  PRIMARY KEY (`artistId`),
  UNIQUE INDEX `artistId_UNIQUE` (`artistId` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulbum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulbum` (
  `ulbumId` INT NOT NULL AUTO_INCREMENT,
  `ulbumName` VARCHAR(45) NULL,
  `artistId` INT NULL,
  `ulbumYear` DATE NULL,
  PRIMARY KEY (`ulbumId`),
  UNIQUE INDEX `artistId_UNIQUE` (`artistId` ASC) VISIBLE,
  CONSTRAINT `artistId`
    FOREIGN KEY (`artistId`)
    REFERENCES `mydb`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`songs` (
  `songsId` INT NOT NULL,
  `songsName` VARCHAR(45) NULL,
  `ulbumID` INT NOT NULL,
  `songsDownloads` INT NOT NULL AUTO_INCREMENT,
  `otherArtist` VARCHAR(45) NULL,
  PRIMARY KEY (`songsId`, `ulbumID`),
  UNIQUE INDEX `ulbumID_UNIQUE` (`ulbumID` ASC) VISIBLE,
  CONSTRAINT `artistId`
    FOREIGN KEY (`songsId`)
    REFERENCES `mydb`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ulbumId`
    FOREIGN KEY (`ulbumID`)
    REFERENCES `mydb`.`ulbum` (`ulbumId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`graphics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`graphics` (
  `graphicsId` INT NOT NULL AUTO_INCREMENT,
  `graphicsName` VARCHAR(45) NULL,
  `graphicsType` VARCHAR(45) NULL,
  PRIMARY KEY (`graphicsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`graphicPrice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`graphicPrice` (
  `graphicPriceId` INT NOT NULL AUTO_INCREMENT,
  `graphicPrice` INT NOT NULL,
  `graphicPriceType` VARCHAR(45) NULL,
  INDEX `graphicPriceId_idx` (`graphicPriceId` ASC) VISIBLE,
  CONSTRAINT `graphicPriceId`
    FOREIGN KEY (`graphicPriceId`)
    REFERENCES `mydb`.`graphics` (`graphicsId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artistInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artistInfo` (
  `artistInfoId` INT NOT NULL,
  `nickName` VARCHAR(45) NULL,
  `artistInfoGen` VARCHAR(45) NULL,
  PRIMARY KEY (`artistInfoId`),
  CONSTRAINT `artistId`
    FOREIGN KEY (`artistInfoId`)
    REFERENCES `mydb`.`artist` (`artistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
